---
project:
  name: Log4brains
  tz: Europe/Paris
  adrFolder: ./docs/adr
  createAdrLink: "#"
  repository:
    url: "https://www.google.com"
    provider: generic
    viewFileUriPattern: /-/edit/main/%path

  packages:
    - name: core
      path: ./packages/core
      adrFolder: ./packages/core/docs/adr

    - name: web
      path: ./packages/web
      adrFolder: ./packages/web/docs/adr
